services:
  grafana:
    image: grafana/grafana-enterprise:12.2.1-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_storage:/etc/prometheus
    command: '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring

  webapp:
    build: .
    container_name: my-webapp
    ports:
      - "8090:80"
    volumes:
      - /root/grafana-prometheus:/grafana-prometheus
      - webapp_storage:/path/in/webapp
    networks:
      - monitoring
      
  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"  # Default port for node-exporter
    networks:
      - monitoring
    restart: always  # Optional: ensure the container restarts on failure

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_storage:
  prometheus_storage:
  webapp_storage:

