services:
  grafana:
    image: grafana/grafana-enterprise:12.2.1-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      monitoring:
        ipv4_address: 172.25.0.11

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${HOME}/grafana-prometheus/prometheus:/etc/prometheus
    command: '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      monitoring:
        ipv4_address: 172.25.0.12

  webapp:
    build: .
    container_name: my-webapp
    ports:
      - "8090:80"
      - "9101:9100"  # node-exporter from webapp container
    volumes:
      - /root/grafana-prometheus:/grafana-prometheus
      - webapp_storage:/path/in/webapp
    networks:
      monitoring:
        ipv4_address: 172.25.0.21

  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"  # Default port for node-exporter
    networks:
      monitoring:
        ipv4_address: 172.25.0.22
    restart: always

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  grafana_storage:
  webapp_storage:
